version: "2"
services:
  ryze-nginx:
    build: ./services/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/nginx/nginx-dev.conf:/etc/nginx/nginx.conf
    volumes_from:
      - ryze-api-php
      - ryze-portal-php
    depends_on:
      - ryze-api-php
      - ryze-portal-php
  ryze-api-php:
    build: ./services/api
    volumes:
      - ./services/api:/app/api
      - ./xdebug.ini:/etc/php7/conf.d/xdebug.ini
      - ./.env:/app/api/.env
    ports:
      - "8000:8000" # For Artisan Serve
    depends_on:
      - db
      - redis
  ryze-portal-php:
    build: ./services/portal
    volumes:
      - ./services/portal:/app/portal
      - ./xdebug.ini:/etc/php7/conf.d/xdebug.ini
      - ./.env:/app/portal/.env
    ports:
      - "8001:8000" # For Artisan Serve
    depends_on:
      - db
      - redis
  redis:
    image: redis:3.2.8-alpine
  db:
    image: wangxian/alpine-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./tmp/data:/var/lib/mysql
